-- plugins/lsp.lua





-- return {
--     "neovim/nvim-lspconfig",
--     dependencies = {
--         "williamboman/mason.nvim",
--         "williamboman/mason-lspconfig.nvim",
--         "hrsh7th/cmp-nvim-lsp",
--         "hrsh7th/cmp-buffer",
--         "hrsh7th/cmp-path",
--         "hrsh7th/cmp-cmdline",
--         "hrsh7th/nvim-cmp",
--         "L3MON4D3/LuaSnip",
--         "saadparwaiz1/cmp_luasnip",
--         "j-hui/fidget.nvim",
--     },
--
--     config = function()
--         local cmp = require('cmp')
--         local cmp_lsp = require("cmp_nvim_lsp")
--         local capabilities = vim.tbl_deep_extend(
--             "force",
--             {},
--             vim.lsp.protocol.make_client_capabilities(),
--             cmp_lsp.default_capabilities())
--
--         require("fidget").setup({})
--         require("mason").setup()
--         require("mason-lspconfig").setup({
--             ensure_installed = {
--                 "lua_ls",
--                 "ts_ls",
--                 "html",
--                 "cssls",
--                 "pyright",
--                 "clangd",
--                 "sqlls",
--             },
--             handlers = {
--                 function(server_name) -- default handler (optional)
--
--                     require("lspconfig")[server_name].setup {
--                         capabilities = capabilities
--                     }
--                 end,
--
--                 ["lua_ls"] = function()
--                     local lspconfig = require("lspconfig")
--                     lspconfig.lua_ls.setup {
--                         capabilities = capabilities,
--                         settings = {
--                             Lua = {
--                                 diagnostics = {
--                                     globals = { "vim", "it", "describe", "before_each", "after_each" },
--                                 }
--                             }
--                         }
--                     }
--                 end,
--
--                 -- TypeScript/JavaScript configuration
--                 ["ts_ls"] = function()
--                     local lspconfig = require("lspconfig")
--                     lspconfig.ts_ls.setup {
--                         capabilities = capabilities,
--                         settings = {
--                             typescript = {
--                                 inlayHints = {
--                                     includeInlayParameterNameHints = "all",
--                                     includeInlayParameterNameHintsWhenArgumentMatchesName = false,
--                                     includeInlayFunctionParameterTypeHints = true,
--                                     includeInlayVariableTypeHints = true,
--                                     includeInlayPropertyDeclarationTypeHints = true,
--                                     includeInlayFunctionLikeReturnTypeHints = true,
--                                     includeInlayEnumMemberValueHints = true,
--                                 },
--                             },
--                             javascript = {
--                                 inlayHints = {
--                                     includeInlayParameterNameHints = "all",
--                                     includeInlayParameterNameHintsWhenArgumentMatchesName = false,
--                                     includeInlayFunctionParameterTypeHints = true,
--                                     includeInlayVariableTypeHints = true,
--                                     includeInlayPropertyDeclarationTypeHints = true,
--                                     includeInlayFunctionLikeReturnTypeHints = true,
--                                     includeInlayEnumMemberValueHints = true,
--                                 },
--                             },
--                         },
--                     }
--                 end,
--
--                 -- HTML configuration
--                 ["html"] = function()
--                     local lspconfig = require("lspconfig")
--                     lspconfig.html.setup {
--                         capabilities = capabilities,
--                         filetypes = { "html", "htmldjango" }, -- Optional: Include Django templates
--                     }
--                 end,
--
--                 -- CSS configuration
--                 ["cssls"] = function()
--                     local lspconfig = require("lspconfig")
--                     lspconfig.cssls.setup {
--                         capabilities = capabilities,
--                         settings = {
--                             css = {
--                                 validate = true,
--                                 lint = {
--                                     unknownAtRules = "ignore", -- Ignore unknown at-rules for modern CSS
--                                 },
--                             },
--                             scss = {
--                                 validate = true,
--                             },
--                             less = {
--                                 validate = true,
--                             },
--                         },
--                     }
--                 end,
--
--                 -- Python configuration
--                 ["pyright"] = function()
--                     local lspconfig = require("lspconfig")
--                     lspconfig.pyright.setup {
--                         capabilities = capabilities,
--                         settings = {
--                             python = {
--                                 analysis = {
--                                     autoSearchPaths = true,
--                                     useLibraryCodeForTypes = true,
--                                     diagnosticMode = "workspace",
--                                 },
--                             },
--                         },
--                     }
--                 end,
--
--                 -- C++ configuration
--                 ["clangd"] = function()
--                     local lspconfig = require("lspconfig")
--                     lspconfig.clangd.setup {
--                         capabilities = capabilities,
--                         -- cmd = {
--                         --     "clangd",
--                         --     "--background-index",
--                         --     "--suggest-missing-includes",
--                         --     "--clang-tidy",
--                         --     "--header-insertion=iwyu",
--                         -- },
--                         cmd = {},
--                     }
--                 end,
--
--             }
--         })
--
--         local cmp_select = { behavior = cmp.SelectBehavior.Select }
--
--         cmp.setup({
--             snippet = {
--                 expand = function(args)
--                     require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
--                 end,
--             },
--             mapping = cmp.mapping.preset.insert({
--                 ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
--                 ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
--                 ['<C-y>'] = cmp.mapping.confirm({ select = true }),
--                 ["<C-Space>"] = cmp.mapping.complete(),
--             }),
--             sources = cmp.config.sources({
--                 { name = 'nvim_lsp' },
--                 { name = 'luasnip' }, -- For luasnip users.
--             }, {
--                 { name = 'buffer' },
--             })
--         })
--
--         vim.diagnostic.config({
--             -- update_in_insert = true,
--             float = {
--                 focusable = false,
--                 style = "minimal",
--                 border = "rounded",
--                 source = "always",
--                 header = "",
--                 prefix = "",
--             },
--         })
--     end
-- }
